'use client'

import { motion, useInView } from 'framer-motion'
import { useRef } from 'react'
import Image from 'next/image'
import { ArrowRight } from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'

function FadeInBlock({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: '-50px' })

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 30 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
      transition={{ duration: 0.6, delay, ease: 'easeOut' }}
    >
      {children}
    </motion.div>
  )
}

type CaseStudy = {
  name: string
  roleFr: string
  roleEn: string
  contextFr: string
  contextEn: string
  descFr: string
  descEn: string
  heroStat: string
  metricFr: string
  metricEn: string
  beforeAfterFr?: string
  beforeAfterEn?: string
  photo: string
  positive: boolean
}

const CASE_STUDIES: CaseStudy[] = [
  {
    name: 'Marguerite Demoures',
    roleFr: 'Experte CRM B2B',
    roleEn: 'B2B CRM Expert',
    contextFr: 'Certifiée HubSpot & ActiveCampaign · Stratégie LinkedIn',
    contextEn: 'HubSpot & ActiveCampaign Certified · LinkedIn Strategy',
    descFr: 'A doublé son pipeline commercial en un seul mois grâce aux contenus générés par Empire.',
    descEn: 'Doubled her sales pipeline in a single month thanks to content generated by Empire.',
    heroStat: '+100%',
    metricFr: 'Pipeline commercial',
    metricEn: 'Sales pipeline',
    beforeAfterFr: 'x1 → x2 en 1 mois',
    beforeAfterEn: 'x1 → x2 in 1 month',
    photo: '/case-studies/marguerite-demoures.png',
    positive: true,
  },
  {
    name: 'Evelyne Guitard',
    roleFr: 'Formatrice',
    roleEn: 'Trainer',
    contextFr: 'Personal branding · LinkedIn',
    contextEn: 'Personal branding · LinkedIn',
    descFr: 'En 21 jours après son onboarding, elle a dépassé les 100 000 vues sur ses contenus LinkedIn.',
    descEn: 'Within 21 days of onboarding, she surpassed 100,000 views on her LinkedIn content.',
    heroStat: '100K',
    metricFr: 'Vues en 21 jours',
    metricEn: 'Views in 21 days',
    beforeAfterFr: '0 → 100 000 vues',
    beforeAfterEn: '0 → 100,000 views',
    photo: '/case-studies/evelyne-guitard.jpg',
    positive: true,
  },
  {
    name: 'Caroline Blivet',
    roleFr: 'Créatrice de contenu',
    roleEn: 'Content Creator',
    contextFr: 'Lancement LinkedIn · Contenus organiques',
    contextEn: 'LinkedIn launch · Organic content',
    descFr: 'Son premier post avec Empire a généré 8 000 impressions. Son record précédent était 361.',
    descEn: 'Her first post with Empire generated 8,000 impressions. Her previous record was 361.',
    heroStat: '+2 116%',
    metricFr: 'Impressions par post',
    metricEn: 'Impressions per post',
    beforeAfterFr: '361 → 8 000',
    beforeAfterEn: '361 → 8,000',
    photo: '/case-studies/caroline-blivet.jpg',
    positive: true,
  },
  {
    name: 'Deborah Guillotin',
    roleFr: 'MyES France',
    roleEn: 'MyES France',
    contextFr: 'Lancement Substack · Communauté',
    contextEn: 'Substack launch · Community',
    descFr: 'Lancée sur Substack sur les conseils de Kevin. Des chiffres incroyables dès le premier post : 10 000 abonnés en moins d\'un mois.',
    descEn: 'Launched on Substack on Kevin\'s advice. Incredible numbers from the first post: 10,000 subscribers in under a month.',
    heroStat: '10K',
    metricFr: 'Abonnés',
    metricEn: 'Subscribers',
    beforeAfterFr: '0 → 10 000 en < 1 mois',
    beforeAfterEn: '0 → 10,000 in < 1 month',
    photo: '/case-studies/deborah-guillotin.png',
    positive: true,
  },
  {
    name: 'Olivier Sarezinski',
    roleFr: 'Gérant Associé',
    roleEn: 'Managing Partner',
    contextFr: 'Contenus quotidiens · Multi-plateforme',
    contextEn: 'Daily content · Multi-platform',
    descFr: 'Passé d\'une activité irrégulière et amatrice à des contenus quotidiens sur tous les réseaux. Le tout en 1h par semaine au lieu de faire appel à plusieurs freelances.',
    descEn: 'Went from irregular, amateur posting to daily content across all platforms. All in 1 hour per week instead of hiring multiple freelancers.',
    heroStat: '1h',
    metricFr: 'Par semaine',
    metricEn: 'Per week',
    beforeAfterFr: 'Plusieurs freelances → 1h/semaine',
    beforeAfterEn: 'Multiple freelancers → 1h/week',
    photo: '/case-studies/olivier-sarezinski.jpg',
    positive: true,
  },
  {
    name: 'Sophie Guibaud',
    roleFr: 'NED indépendante & Growth Advisor',
    roleEn: 'Independent NED & Growth Advisor',
    contextFr: 'Thought leadership · Advisory',
    contextEn: 'Thought leadership · Advisory',
    descFr: 'Partage ses idées de façon rapide, claire et systématique. Des heures gagnées chaque semaine qu\'elle consacre à accompagner ses entrepreneurs.',
    descEn: 'Shares her ideas quickly, clearly and systematically. Hours saved every week that she dedicates to supporting her entrepreneurs.',
    heroStat: '10h',
    metricFr: 'Économisées par semaine',
    metricEn: 'Saved per week',
    photo: '/case-studies/sophie-guibaud.jpg',
    positive: true,
  },
]

export default function CaseStudiesSection() {
  const { lang, t } = useLanguage()
  const fr = lang === 'fr'

  return (
    <section className="relative w-full py-20 md:py-28 overflow-hidden bg-gradient-to-b from-black via-[#0a0a0a] to-black">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_50%,rgb(var(--empire-rgb)_/_0.04),transparent)]" />

      <div className="container relative z-10">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <FadeInBlock>
            <div className="text-center mb-14">
              <p className="text-xs text-empire uppercase tracking-widest mb-3">
                {fr ? 'Résultats clients' : 'Client Results'}
              </p>
              <h2 className="text-3xl md:text-5xl font-bold text-white mb-4">
                {fr
                  ? <>{t.caseStudies?.title || 'Des résultats concrets,'} <span className="text-empire">{t.caseStudies?.titleHighlight || 'dès le premier mois'}</span></>
                  : <>{t.caseStudies?.title || 'Real results,'} <span className="text-empire">{t.caseStudies?.titleHighlight || 'from month one'}</span></>}
              </h2>
              <p className="text-neutral-400 text-lg max-w-2xl mx-auto">
                {fr
                  ? 'Des chiffres tirés directement des dashboards de nos clients. Pas inventés.'
                  : 'Numbers pulled straight from each client\'s dashboard. Not made up.'}
              </p>
            </div>
          </FadeInBlock>

          {/* Case Study Cards - 2 columns */}
          <div className="grid md:grid-cols-2 gap-5">
            {CASE_STUDIES.map((cs, i) => (
              <FadeInBlock key={cs.name} delay={0.05 + i * 0.06}>
                <div className="relative h-full rounded-2xl border border-white/10 bg-white/[0.03] overflow-hidden hover:border-empire/30 transition-colors">
                  {/* Top: Client info bar */}
                  <div className="flex items-center gap-3 px-6 pt-5 pb-4">
                    <div className="relative h-10 w-10 shrink-0 rounded-full overflow-hidden border-2 border-empire/30">
                      <Image src={cs.photo} alt={cs.name} fill className="object-cover" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-white truncate">{cs.name}</p>
                      <p className="text-xs text-neutral-500 truncate">{fr ? cs.roleFr : cs.roleEn} · {fr ? cs.contextFr : cs.contextEn}</p>
                    </div>
                  </div>

                  {/* Description */}
                  <div className="px-6 pb-5">
                    <p className="text-[14px] text-neutral-300 leading-relaxed">
                      {fr ? cs.descFr : cs.descEn}
                    </p>
                  </div>

                  {/* Bottom: Stats bar */}
                  <div className="border-t border-white/[0.06] bg-white/[0.02] px-6 py-4">
                    <div className="flex items-center gap-6">
                      {/* Hero stat */}
                      <div className="shrink-0">
                        <p className="text-3xl md:text-4xl font-black text-empire leading-none">{cs.heroStat}</p>
                        <p className="text-[11px] text-neutral-400 mt-1 font-medium">{fr ? cs.metricFr : cs.metricEn}</p>
                      </div>

                      {/* Before → After */}
                      {(fr ? cs.beforeAfterFr : cs.beforeAfterEn) && (
                        <div className="flex-1 min-w-0">
                          <div className="inline-flex items-center gap-2 rounded-lg bg-empire/10 border border-empire/20 px-3 py-1.5">
                            <span className="text-xs font-mono font-semibold text-neutral-300">
                              {fr ? cs.beforeAfterFr : cs.beforeAfterEn}
                            </span>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </FadeInBlock>
            ))}
          </div>

          {/* CTA */}
          <FadeInBlock delay={0.5}>
            <div className="mt-12 text-center">
              <a
                href="#pricing"
                className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-empire text-black font-bold text-lg hover:scale-105 transition-transform shadow-[0_0_30px_rgb(var(--empire-rgb)_/_0.3)]"
              >
                {fr ? 'Obtenir les mêmes résultats' : 'Get the same results'}
                <ArrowRight size={20} />
              </a>
              <p className="mt-3 text-xs text-neutral-500">
                {fr ? '7 jours d\'essai gratuit · Sans engagement' : '7-day free trial · No commitment'}
              </p>
            </div>
          </FadeInBlock>
        </div>
      </div>
    </section>
  )
}
