'use client'

import { motion, useInView } from 'framer-motion'
import { useRef, useState } from 'react'
import Image from 'next/image'
import { ArrowRight } from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'
import { useAutopilot } from '@/contexts/AutopilotContext'

function FadeInBlock({ children, delay = 0, className }: { children: React.ReactNode; delay?: number; className?: string }) {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: '-50px' })

  return (
    <motion.div
      ref={ref}
      className={className}
      initial={{ opacity: 0, y: 30 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
      transition={{ duration: 0.6, delay, ease: 'easeOut' }}
    >
      {children}
    </motion.div>
  )
}

type CaseStudy = {
  name: string
  roleFr: string
  roleEn: string
  contextFr: string
  contextEn: string
  descFr: string
  descEn: string
  heroStat: string
  metricFr: string
  metricEn: string
  beforeAfterFr?: string
  beforeAfterEn?: string
  photo: string
  positive: boolean
}

const CASE_STUDIES: CaseStudy[] = [
  {
    name: 'Marguerite Demoures',
    roleFr: 'Experte CRM B2B',
    roleEn: 'B2B CRM Expert',
    contextFr: 'Certifiée HubSpot & ActiveCampaign · Stratégie LinkedIn',
    contextEn: 'HubSpot & ActiveCampaign Certified · LinkedIn Strategy',
    descFr: 'A doublé son pipeline commercial en un seul mois grâce aux contenus générés par Empire.',
    descEn: 'Doubled her sales pipeline in a single month thanks to content generated by Empire.',
    heroStat: '+100%',
    metricFr: 'Pipeline commercial',
    metricEn: 'Sales pipeline',
    beforeAfterFr: 'x1 → x2 en 1 mois',
    beforeAfterEn: 'x1 → x2 in 1 month',
    photo: '/case-studies/marguerite-demoures.png',
    positive: true,
  },
  {
    name: 'Evelyne Guitard',
    roleFr: 'Formatrice',
    roleEn: 'Trainer',
    contextFr: 'Personal branding · LinkedIn',
    contextEn: 'Personal branding · LinkedIn',
    descFr: 'En 21 jours après son onboarding, elle a dépassé les 100 000 vues sur ses contenus LinkedIn.',
    descEn: 'Within 21 days of onboarding, she surpassed 100,000 views on her LinkedIn content.',
    heroStat: '100K',
    metricFr: 'Vues en 21 jours',
    metricEn: 'Views in 21 days',
    beforeAfterFr: '0 → 100 000 vues',
    beforeAfterEn: '0 → 100,000 views',
    photo: '/case-studies/evelyne-guitard.jpg',
    positive: true,
  },
  {
    name: 'Caroline Blivet',
    roleFr: 'Créatrice de contenu',
    roleEn: 'Content Creator',
    contextFr: 'Lancement LinkedIn · Contenus organiques',
    contextEn: 'LinkedIn launch · Organic content',
    descFr: 'Son premier post avec Empire a généré 8 000 impressions. Son record précédent était 361.',
    descEn: 'Her first post with Empire generated 8,000 impressions. Her previous record was 361.',
    heroStat: '+2 116%',
    metricFr: 'Impressions par post',
    metricEn: 'Impressions per post',
    beforeAfterFr: '361 → 8 000',
    beforeAfterEn: '361 → 8,000',
    photo: '/case-studies/caroline-blivet.jpg',
    positive: true,
  },
  {
    name: 'Deborah Guillotin',
    roleFr: 'MyES France',
    roleEn: 'MyES France',
    contextFr: 'Lancement Substack · Communauté',
    contextEn: 'Substack launch · Community',
    descFr: 'Lancée sur Substack sur les conseils de Kevin. Des chiffres incroyables dès le premier post : 10 000 abonnés en moins d\'un mois.',
    descEn: 'Launched on Substack on Kevin\'s advice. Incredible numbers from the first post: 10,000 subscribers in under a month.',
    heroStat: '10K',
    metricFr: 'Abonnés',
    metricEn: 'Subscribers',
    beforeAfterFr: '0 → 10 000 en < 1 mois',
    beforeAfterEn: '0 → 10,000 in < 1 month',
    photo: '/case-studies/deborah-guillotin.png',
    positive: true,
  },
  {
    name: 'Olivier Sarezinski',
    roleFr: 'Gérant Associé',
    roleEn: 'Managing Partner',
    contextFr: 'Contenus quotidiens · Multi-plateforme',
    contextEn: 'Daily content · Multi-platform',
    descFr: 'Passé d\'une activité irrégulière et amatrice à des contenus quotidiens sur tous les réseaux. Le tout en 1h par semaine au lieu de faire appel à plusieurs freelances.',
    descEn: 'Went from irregular, amateur posting to daily content across all platforms. All in 1 hour per week instead of hiring multiple freelancers.',
    heroStat: '1h',
    metricFr: 'Par semaine',
    metricEn: 'Per week',
    beforeAfterFr: 'Plusieurs freelances → 1h/semaine',
    beforeAfterEn: 'Multiple freelancers → 1h/week',
    photo: '/case-studies/olivier-sarezinski.jpg',
    positive: true,
  },
  {
    name: 'Sophie Guibaud',
    roleFr: 'NED indépendante & Growth Advisor',
    roleEn: 'Independent NED & Growth Advisor',
    contextFr: 'Thought leadership · Advisory',
    contextEn: 'Thought leadership · Advisory',
    descFr: 'Partage ses idées de façon rapide, claire et systématique. Des heures gagnées chaque semaine qu\'elle consacre à accompagner ses entrepreneurs.',
    descEn: 'Shares her ideas quickly, clearly and systematically. Hours saved every week that she dedicates to supporting her entrepreneurs.',
    heroStat: '10h',
    metricFr: 'Économisées par semaine',
    metricEn: 'Saved per week',
    photo: '/case-studies/sophie-guibaud.jpg',
    positive: true,
  },
]

/** Nombre de cartes visibles sur mobile avant le bouton « voir les autres ». */
const MOBILE_VISIBLE = 3

export default function CaseStudiesSection() {
  const { lang, t } = useLanguage()
  const { autopilot } = useAutopilot()
  const fr = lang === 'fr'
  const [showAll, setShowAll] = useState(false)

  // Légende keeps a single aggregate proof point instead of individual stories.
  if (autopilot) return null

  return (
    <section className="relative w-full py-12 md:py-16 overflow-hidden bg-gradient-to-b from-black via-[#0a0a0a] to-black">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_50%,rgb(var(--empire-rgb)_/_0.04),transparent)]" />

      <div className="container relative z-10">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <FadeInBlock>
            <div className="text-center mb-14">
              <p className="text-xs text-empire uppercase tracking-widest mb-3">
                {fr ? 'Résultats clients' : 'Client Results'}
              </p>
              <h2 className="text-3xl md:text-5xl font-bold text-white mb-4">
                {fr
                  ? <>{t.caseStudies?.title || 'Des résultats concrets,'} <span className="text-empire">{t.caseStudies?.titleHighlight || 'dès le premier mois'}</span></>
                  : <>{t.caseStudies?.title || 'Real results,'} <span className="text-empire">{t.caseStudies?.titleHighlight || 'from month one'}</span></>}
              </h2>
              <p className="text-neutral-400 text-lg max-w-2xl mx-auto">
                {fr
                  ? 'Des chiffres tirés directement des dashboards de nos clients. Pas inventés.'
                  : 'Numbers pulled straight from each client\'s dashboard. Not made up.'}
              </p>
            </div>
          </FadeInBlock>

          {/* Cartes : grille deux colonnes à partir de md. Sur mobile, trois
              cartes empilées et un bouton pour les trois autres - pas de rail
              horizontal, il volait le scroll vertical. Les textes passent à la
              ligne au lieu d'être tronqués à droite. */}
          <div className="grid gap-4 md:grid-cols-2 md:gap-5">
            {CASE_STUDIES.map((cs, i) => (
              <FadeInBlock
                key={cs.name}
                delay={0.05 + i * 0.06}
                className={i >= MOBILE_VISIBLE && !showAll ? 'hidden md:block' : undefined}
              >
                <div className="relative flex h-full flex-col overflow-hidden rounded-2xl border border-white/[0.14] bg-white/[0.05] transition-colors hover:border-empire/30">
                  {/* Top: Client info bar */}
                  <div className="flex items-center gap-3 px-5 pt-5 pb-3 md:px-6 md:pb-4">
                    <div className="relative h-10 w-10 shrink-0 rounded-full overflow-hidden border-2 border-empire/30">
                      <Image src={cs.photo} alt={cs.name} fill className="object-cover" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-white">{cs.name}</p>
                      <p className="text-xs leading-snug text-neutral-400">{fr ? cs.roleFr : cs.roleEn} · {fr ? cs.contextFr : cs.contextEn}</p>
                    </div>
                  </div>

                  {/* Description */}
                  <div className="flex-1 px-5 pb-4 md:px-6 md:pb-5">
                    <p className="text-[14px] text-neutral-300 leading-relaxed">
                      {fr ? cs.descFr : cs.descEn}
                    </p>
                  </div>

                  {/* Bottom: Stats bar */}
                  <div className="border-t border-white/[0.08] bg-white/[0.03] px-5 py-4 md:px-6">
                    <div className="flex flex-wrap items-center gap-x-5 gap-y-2">
                      {/* Hero stat */}
                      <div className="shrink-0">
                        <p className="text-3xl md:text-4xl font-black text-empire leading-none">{cs.heroStat}</p>
                        <p className="text-[11px] text-neutral-400 mt-1 font-medium">{fr ? cs.metricFr : cs.metricEn}</p>
                      </div>

                      {/* Before → After */}
                      {(fr ? cs.beforeAfterFr : cs.beforeAfterEn) && (
                        <div className="inline-flex items-center rounded-lg bg-empire/10 border border-empire/20 px-3 py-1.5">
                          <span className="text-xs font-mono font-semibold text-neutral-300">
                            {fr ? cs.beforeAfterFr : cs.beforeAfterEn}
                          </span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </FadeInBlock>
            ))}
          </div>
          {!showAll && (
            <button
              type="button"
              onClick={() => setShowAll(true)}
              className="mt-4 w-full rounded-xl border border-white/15 bg-white/[0.04] px-4 py-3 text-sm font-semibold text-neutral-200 transition hover:border-white/30 hover:bg-white/[0.07] md:hidden"
            >
              {fr
                ? `Voir les ${CASE_STUDIES.length - MOBILE_VISIBLE} autres résultats`
                : `See the ${CASE_STUDIES.length - MOBILE_VISIBLE} other results`}
            </button>
          )}

          {/* CTA */}
          <FadeInBlock delay={0.5}>
            <div className="mt-12 text-center">
              <a
                href="/postuler"
                className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-empire text-black font-bold text-lg hover:scale-105 transition-transform shadow-[0_0_30px_rgb(var(--empire-rgb)_/_0.3)]"
              >
                {fr ? 'Recevoir un accès' : 'Get access'}
                <ArrowRight size={20} />
              </a>
              <p className="mt-3 text-xs text-neutral-500">
                {fr ? 'Sur sélection' : 'By selection'}
              </p>
            </div>
          </FadeInBlock>
        </div>
      </div>
    </section>
  )
}
